[vpnc] Switch to new upstream and update to 0.5.3.r524
sailfishos/vpnc pull request #1
Opened 2023-01-17 09:19 UTC by Thaodan

Switch to new upstream and update to 0.5.3.r524.
Remove old packaging cruft that was imported from Fedora, most of
these were related to the vpnc script that we don't use.
Switch anything besides vpnc programs such as default config, which
was only used if vpnc was started outside of a connection manager, to
the documentation package.

2023-01-17 09:35 UTC, LaakkonenJussi requested changes
Got this when building:
```
install -m644 src/doc/*.md /path/to/vpnc/installroot/usr/share/doc/vpnc
install: cannot stat 'src/doc/*.md': No such file or directory
make: *** [Makefile:153: install-doc] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.7RgVjU (%install)
```

And we do not need the old source `vpnc-0.5.3.tar.gz` after this change, right? And the patches apply only to that so those became obsolete as well?

2023-01-17 09:40 UTC, Thaodan commented
> Got this when building:
> 
> ```
> install -m644 src/doc/*.md /path/to/vpnc/installroot/usr/share/doc/vpnc
> install: cannot stat 'src/doc/*.md': No such file or directory
> make: *** [Makefile:153: install-doc] Error 1
> error: Bad exit status from /var/tmp/rpm-tmp.7RgVjU (%install)
> ```

Do you have all the submodules?

> And we do not need the old source `vpnc-0.5.3.tar.gz` after this change, right? And the patches apply only to that so those became obsolete as well?

Oh yeah I forgot those fixed.

2023-01-17 10:24 UTC, LaakkonenJussi commented
> > Got this when building:
> > ```
> > install -m644 src/doc/*.md /path/to/vpnc/installroot/usr/share/doc/vpnc
> > install: cannot stat 'src/doc/*.md': No such file or directory
> > make: *** [Makefile:153: install-doc] Error 1
> > error: Bad exit status from /var/tmp/rpm-tmp.7RgVjU (%install)
> > ```
> 
> Do you have all the submodules?

Yep, ran the common
```
git submodule init
git submodule update
```
prior build.

2023-01-17 16:13 UTC, Thaodan commented
Jussi Laakkonen ***@***.***> writes:

> Yep, ran the common
> ```
> git submodule init
> git submodule update
> ```
> prior build.

Try `git submodule update --init --recursive`.

2023-01-17 16:35 UTC, LaakkonenJussi commented
> Try `git submodule update --init --recursive`.

Yeah that did it. Apparently the docs isn't updated without `--recursive`.

Maybe we should get rid of at least the rpm errors when doing this kind of package reformatting:
`vpnc-pcf2vpnc.aarch64: E: incorrect-fsf-address /usr/bin/pcf2vpnc`

I'll test this tomorrow as it now builds.

2023-01-17 16:37 UTC, LaakkonenJussi requested changes
Otherwise seems ok now.
But we could get rid of this kind of RPM errors still:
`vpnc-pcf2vpnc.aarch64: E: incorrect-fsf-address /usr/bin/pcf2vpnc`

2023-01-17 18:02 UTC, Thaodan commented
Jussi Laakkonen ***@***.***> writes:

> Otherwise seems ok now.
> But we could get rid of this kind of RPM errors still:
> `vpnc-pcf2vpnc.aarch64: E: incorrect-fsf-address /usr/bin/pcf2vpnc`

Reported: https://github.com/streambinder/vpnc/issues/39

2023-01-18 09:59 UTC, saukko commented on rpm/vpnc.spec
> +Group:          Applications/Internet
Drop group

2023-01-18 09:59 UTC, saukko commented on rpm/vpnc.spec
> +License:        GPL-2.0-or-later
Not according to what we use, see what previous .spec had

2023-01-18 09:59 UTC, saukko commented on rpm/vpnc.spec
> +BuildRequires:  pkgconfig(libgcrypt) > 1.1.90
We should obsolete the consoleuser package here from old packaging?

2023-01-18 09:59 UTC, saukko commented on rpm/vpnc.spec
> +
It is just github not showing the changes to previous .spec or you didn't do git mv for the spec file to see those?

2023-01-18 11:50 UTC, Thaodan commented on rpm/vpnc.spec
> +License:        GPL-2.0-or-later
The license of the package states GPL-2.0 or later it's not about what we use.

2023-01-18 11:51 UTC, Thaodan commented on rpm/vpnc.spec
> +
The changes to spec are so great that git doesn't recognize the move anymore.

2023-01-18 11:53 UTC, Thaodan commented on rpm/vpnc.spec
> +License:        GPL-2.0-or-later
We follow the Fedora guidelines for package license which states:
> "Each license identifier in the SPDX expression forming the License: field must correspond to a license that is [allowed](https://docs.fedoraproject.org/en-US/legal/allowed-licenses/) by Fedora for the appropriate category of material. In rare cases Fedora may grant limited exceptions permitting otherwise not-allowed licenses for specific packages or under other specific conditions; this will be noted in the TOML file for the license in the Fedora License Data repository."

https://docs.fedoraproject.org/en-US/legal/license-field/

2023-01-23 10:10 UTC, Thaodan commented on rpm/vpnc.spec
> +BuildRequires:  pkgconfig(libgcrypt) > 1.1.90
Those were never preinstalled and technically still work, however I can still add those.

2023-01-23 10:50 UTC, LaakkonenJussi commented on rpm/vpnc.spec
> +Group:          Applications/Internet
Yeah we do not use `Group` anywhere in the spec-files.

2023-01-23 11:22 UTC, LaakkonenJussi approved these changes
LGTM, tested, seems to work with libreswan VPN server. Not taking stance on the licensing issue.

Just drop `Group` from spec and then it is fine for me.

2023-01-23 11:38 UTC, merged